config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :kittens
  root 'kittens#index'
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/kitten.rb
class Kitten < ApplicationRecord
    validates :name, presence: true
    validates :age, presence: true
    validates :cuteness, presence: true
    validates :softness, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/kittens_controller.rb
class KittensController < ApplicationController
    before_action :set_kitten, only: [:show, :edit, :update, :destroy]

    def index
      @kittens = Kitten.all
    end
  
    def show
    end
  
    def new
      @kitten = Kitten.new
    end
  
    def create
        @kitten = Kitten.new(kitten_params)
      
        if @kitten.save
          puts "SAVE BLOCK TRIGGERED!!!!!!!"
          puts @kitten
          flash[:success] = "Congratulations! Kitten was successfully saved"
          redirect_to @kitten
        else
          puts "SAVE FAILED!!!!!!!"
          puts @kitten
          
          flash.now[:error] = 'Oops! There was an error in the form. Please correct it.'
          render :new
        end
      end
      
    def edit
    end
  
    def update
      if @kitten.update(kitten_params)
        flash[:success] = "Congratulations! Kitten was successfully updated."
        redirect_to @kitten
      else
        flash.now[:error] = "Oops! There was an error in the form. Please correct it."
        render :edit
      end
    end
  
    def destroy
      @kitten.destroy
      flash[:success] = "Congratulations! Kitten was successfully destroyed."
      redirect_to kittens_path
    end
  
    private
  
    def set_kitten
      @kitten = Kitten.find(params[:id])
    end
  
    def kitten_params
      params.require(:kitten).permit(:name, :age, :cuteness, :softness)
    end
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/kittens_helper.rb
module KittensHelper
end

app/views/kittens/_form.html.erb
<%= form_with model: @kitten, url: kittens_path, html: { id: 'kitten-form', 'data-turbo': false }, local: true do |form| %>
  <%# if @kitten.errors.any? %>
    <%# <div id="error_explanation"> %>
      <%# <ul> %>
        <%# @kitten.errors.full_messages.each do |message| %>
          <%#li>= message</li>
        <%# end %>
      <%# </ul> %>  
    <%# </div> %>
  <%# end %>

  <div class="field">
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :age %><br>
    <%= form.text_field :age %>
  </div>

  <div class="field">
    <%= form.label :cuteness %><br>
    <%= form.text_field :cuteness %>
  </div>

  <div class="field">
    <%= form.label :softness %><br>
    <%= form.text_field :softness %>
  </div>

  <div class="actions">
    <%= form.button %>
  </div>
<% end %>

app/views/kittens/edit.html.erb
<h1>Edit Kitten</h1>

<%= render 'form', kitten: @kitten %>

<%= link_to 'Show', @kitten %> 
<%= link_to 'Delete', @kitten, method: :delete, data: { confirm: 'Are you sure? ARE YOU REALLY SURE WIPING THIS KITTEN FROM EXISTENCE?' } %> 
<%= link_to 'Back', kittens_path %>

app/views/kittens/index.html.erb
<h1>All Kittens</h1>

<ul>
  <% @kittens.each do |kitten| %>
    <li><%= link_to kitten.name, kitten %></li>
  <% end %>
</ul>

app/views/kittens/new.html.erb
<h1>New Kitten</h1>


<% if flash[:error].present? %>
  <div class="flash error"><%= flash[:error] %></div>
<% end %>

<%= render 'form', kitten: @kitten %>
  

<%= link_to 'Back', kittens_path %>

app/views/kittens/show.html.erb
<h1><%= @kitten.name %></h1>

<p>
  Name: <%= @kitten.name%>
  Age: <%= @kitten.age %><br>
  Cutenss: <%= @kitten.cuteness%>
  Softness: <%= @kitten.softness %>
</p>

<%= link_to 'Edit', edit_kitten_path(@kitten) %> 
<%= link_to 'Delete', @kitten, method: :delete, data: { confirm: 'Are you sure? ARE YOU REALLY SURE WIPING THIS KITTEN FROM EXISTENCE?' } %> |
<%= link_to 'Back', kittens_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OdinKittens</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= javascript_importmap_tags %>

    <style type = "text/css">
          .flash {
        padding: 10px;
        margin-bottom: 10px;
      }

      .flash.success {
        background-color: #a3d699;
        color: #155724;
      }

      .flash.error {
        background-color: #f8d7da;
        color: #721c24;
      }
    </style>

  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
  <!-- Flash messages -->
<% flash.each do |key, value| %>
  <div class="flash <%= key %>"><%= value %></div>
<% end %>
    <%= yield %>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <ul>
      <% object.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>